### ISSUE TITLE
Make canvas responsive

### ISSUE THREAD

**Issue by Davidthecode** [Davidthecode/Stroke#2]
the canvas has a fixed width and is not responsive
file to edit:[https://github.com/Davidthecode/Stroke/blob/main/src/App.tsx](https://github.com/Davidthecode/Stroke/blob/main/src/App.tsx)

**Comment by deeksharungta** [comment]
Hey, I would like to work on this issue. Could you please consider assigning it to me.

**Comment by Davidthecode** [comment]
Sure @deeksharungta
